# STEP 1

server {
    listen 8080;
    server_name localhost;

    # Serve the static blog
    root /var/www/blog;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /stub_status {
        return 404;
    }
}

server {
    listen 127.0.0.1:8079;
    server_name localhost;
    
    # Metrics endpoint is a different port only accessible from localhost
    # Never exposed publicly (Cloudflare Tunnel only routes / with port 8080)
    location = /stub_status {
        stub_status;
        allow 127.0.0.1;
        deny all;
    }
}

# store at /etc/nginx/sites-available/blog
# keep the file owned by root 
# create symlink from /etc/nginx/sites-available/blog to /etc/nginx/sites-enabled/blog
